# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb560f63d968cc794bf6ab293b0a5bbec2d0893f547463a45b76c6985eedca37d0714c2fd684c424ce16076f0adc983d6854c3bd6cb5ae6a60fb531444b97203

test:
  secret_key_base: c163468c5f4bdfea6935b2bccb01cbbaa2e40a7ff72f7a3ca38ea109e1bccbe7005f38bf6cb55dfecc0801d76e91083ded0418b92a5860c26eecf45c0910351b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
